#ifndef WATCH_APP_APP_CONFIG_H
#define WATCH_APP_APP_CONFIG_H

#define WATCH_INPUT_SCAN_PERIOD_MS        10U
#define WATCH_INPUT_DEBOUNCE_MS            30U
#define WATCH_INPUT_LONG_PRESS_MS        1200U

#define WATCH_DISPLAY_REFRESH_MS          100U
#define WATCH_DISPLAY_SLEEP_MS          30000U
#define WATCH_CLOCK_REFRESH_MS            250U
#define WATCH_BATTERY_REFRESH_MS        30000U
#define WATCH_MOTION_REFRESH_MS            20U
#define WATCH_DEVICE_RETRY_MS            2000U

#define WATCH_DEFAULT_BRIGHTNESS_PERCENT   80U
#define WATCH_FIRMWARE_VERSION          "V1.0"

#endif /* WATCH_APP_APP_CONFIG_H */
